# Generated by Django 2.2.4 on 2019-08-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='created',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='updated',
            new_name='fecha_edicion',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='order',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='titulo',
        ),
    ]
