# Generated by Django 2.2.4 on 2019-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message_ultima_vez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ultima_vez',
        ),
    ]
