# Generated by Django 2.2.4 on 2019-09-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_remove_message_ultima_vez'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hilo',
            options={'ordering': ['-fecha_actualizacion']},
        ),
    ]
